{
 "title": "ZFS",
 "description": "Graphs ZFS ARC and ARC L2 Hit %, Hits, Misses, Size, and Zpool",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_zfs_arc_data_size{job=\"node_exporter\"}, instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(node_exporter_build_info{instance=~\"$node:(.*)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ZFS user quota used 185.181.228.4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_user_used_bytes{instance=\"185.181.228.4:9100\"}",
     "legendFormat": "{{dataset}} {{user}}"
    }
   ]
  },
  {
   "title": "ZFS used quota percent 185.181.228.4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "0 < zfs_user_used_bytes{instance=\"185.181.228.4:9100\"} / zfs_user_quota_bytes{instance=\"185.181.228.4:9100\"} <= 100",
     "legendFormat": "{{dataset}} {{user}}"
    }
   ]
  },
  { "title": "Quota used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ZPOOL - Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_rtime{job=\"node_exporter\",instance=\"$node:$port\"}[5m])",
     "legendFormat": "{{zpool}} - read"
    },
    {
     "expr": "irate(node_zfs_zpool_wtime{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{zpool}} - write"
    }
   ]
  },
  {
   "title": "ZPOOL - Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_reads{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{zpool}} - reads"
    },
    {
     "expr": "irate(node_zfs_zpool_writes{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{zpool}} - writes"
    }
   ]
  },
  {
   "title": "ARC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ARC - Hit %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{job=\"node_exporter\",instance=~\"$node:$port\"}[5m]) / (irate(node_zfs_arc_demand_data_hits{job=\"node_exporter\",instance=~\"$node:$port\"}[5m]) + irate(node_zfs_arc_demand_data_misses{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "data"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{job=\"node_exporter\",instance=~\"$node:$port\"}[5m]) / (irate(node_zfs_arc_demand_metadata_hits{job=\"node_exporter\",instance=~\"$node:$port\"}[5m]) + irate(node_zfs_arc_demand_metadata_misses{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "ARC - Hits, Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "data_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "metadata_hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_misses{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "data_misses"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_misses{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "metadata_misses"
    }
   ]
  },
  {
   "title": "ARC - Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{job=\"node_exporter\",instance=~\"$node:$port\"}",
     "legendFormat": "data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{job=\"node_exporter\",instance=~\"$node:$port\"}",
     "legendFormat": "metadata"
    },
    {
     "expr": "node_zfs_arc_anon_size{job=\"node_exporter\",instance=~\"$node:$port\"}",
     "legendFormat": "anon"
    },
    {
     "expr": "node_zfs_arc_hdr_size{job=\"node_exporter\",instance=~\"$node:$port\"}",
     "legendFormat": "hdr"
    },
    {
     "expr": "node_zfs_arc_other_size{job=\"node_exporter\",instance=~\"$node:$port\"}",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "ARC L2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ARC L2 - Hit %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{job=\"node_exporter\",instance=~\"$node:$port\"}[5m]) / (irate(node_zfs_arc_l2_hits{job=\"node_exporter\",instance=~\"$node:$port\"}[5m]) + irate(node_zfs_arc_l2_misses{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "ARC L2 - Hits, Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(node_zfs_arc_l2_misses{job=\"node_exporter\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "ARC L2 - Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_l2_asize{job=\"node_exporter\",instance=~\"$node:$port\"}",
     "legendFormat": "asize"
    },
    {
     "expr": "node_zfs_arc_l2_hdr_size{job=\"node_exporter\",instance=~\"$node:$port\"}",
     "legendFormat": "metadata"
    },
    {
     "expr": "node_zfs_arc_l2_size{job=\"node_exporter\",instance=~\"$node:$port\"}",
     "legendFormat": "size"
    }
   ]
  }
 ]
}